site_name: 'Sabayon Wiki'
site_description: 'Documentation for Sabayon Linux'
site_author: 'Sabayon'
site_url: 'https://sabayon.github.io/wiki-next/'

repo_name: 'Sabayon/wiki-next'
repo_url: https://github.com/Sabayon/wiki-next

nav:
- Home: index.md
- Contributing:
    - Wiki: articles/documentation.md
    - IRC|Testers: articles/irc.md
- Entropy Package Manager: articles/entropy.md
- How To Index: articles/howto.md
theme:
  name: 'material'
extra_css: [extra.css]
