site_name: 'Sabayon wiki'
site_description: 'Documentation for Sabayon Linux'
site_author: 'Sabayon'
site_url: 'https://sabayon.github.io/wiki-next/'

repo_name: 'Sabayon/wiki-next'
repo_url: https://github.com/Sabayon/wiki-next

pages:
- Home: index.md
- Contributing:
    - Wiki: articles/documentation.md
    - IRC|Testers: articles/irc.md
- Entropy Package Manager:
    - Entropy: articles/Entropy.md
    - Fresh Install What to Do: articles/FreshInstall.md
- How To Index:
    - Applications:
    - Hardware:
    - Networking:
        - Web:
            - LAMP: articles/lamp.md
    - System Administration:
        - Security:
        - Desktop Environments:
theme: 'material'
