site_name: 'Sabayon wiki'
site_description: 'Documentation for Sabayon Linux'
site_author: 'Sabayon'
site_url: 'https://sabayon.github.io/wiki-next/'

repo_name: 'Sabayon/wiki-next'
repo_url: https://github.com/Sabayon/wiki-next

pages:
- Home: index.md
- Articles:
    - Documentation: articles/documentation.md
- Entropy Package Manager:
    - Entropy: articles/Entropy - Package Management.md
    - Fresh Install What to Do: articles/Fresh Install - What to Do.md
theme: 'material'
